server:
  port: 8081

spring:
  mongodb:
    uri: mongodb://libraryapp:6ZwTTpXAm6UAp4nnaOFFwWfr2015zs8ikqp0I686dy8y-ghu@ddb53618-2335-4259-b8bc-3ca5e99a8f6a.asia-southeast1.firestore.goog:443/user-db?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

eureka:
  client:
    service-url:
      defaultZone: http://10.10.0.17:8761/eureka/,http://10.10.0.18:8761/eureka/
  instance:
    prefer-ip-address: true
